apiVersion: v1
kind: Namespace
metadata:
  name: research
  labels:
    research.fabric/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: research-system
  labels:
    research.fabric/system: "true"
