apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: research-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YoshiyukiKono/research-fabric-lab.git
    targetRevision: main
    path: deploy/k8s/platform

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
