apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: research-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YoshiyukiKono/research-fabric-lab.git
    targetRevision: main
    path: research-platform/storage/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
